# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - apk update
  - apk upgrade
  - apk add python3 python3-dev build-base git
  - pip3 install docker-compose
  - pip3 install -r requirements.txt
  - git config --global user.email "foo@bar.baz"
  - git config --global user.name "Foo Bar"
#   see the following issue for reasoning: https://gitlab.com/gitlab-org/gitlab-ce/issues/41227
  - export SHARED_PATH="$(dirname ${CI_PROJECT_DIR})/shared"
  - export TPL_PLAYGROUND="${SHARED_PATH}/tpl-playground"
  - mkdir -p $TPL_PLAYGROUND

build:
  stage: build
  script:
    - tox
