{%- raw -%}
- name: "Update nginx include files"
  template:
      src: "nginx/conf.d/{{ item.src }}"
      dest: "/etc/nginx/conf.d/{{ item.dest }}"
  loop:
    - { src: "app.include", dest: "app.{{ project }}.include" }
    - { src: "app.proxy.include", dest: "app.{{ project }}.proxy.include" }
    - { src: "app.proxy_django.include", dest: "app.{{ project }}.proxy_django.include" }
    - { src: "common.django.include", dest: "common.{{ project }}.django.include" }
    - { src: "ssl.include", dest: "ssl.{{ project }}.include" }
    - { src: "map_files.include", dest: "app.{{ project }}.map_files.include" }
{%- endraw -%}
{%- if cookiecutter.frontend_style == 'spa' %}
{%- raw %}
    - { src: "app.proxy_node.include", dest: "app.{{ project }}.proxy_node.include" }
    - { src: "common.node.include", dest: "common.{{ project }}.node.include" }
{%- endraw %}
{%- endif %}
{%- raw %}


- name: "Update nginx config"
  template:
      src: site-nginx.conf
      dest: "/etc/nginx/sites-enabled/{{ project }}"


- name: "Reload nginx"
  shell: "docker exec nginx nginx -t && docker exec nginx nginx -s reload"
{%- endraw %}
