# Hostnames for the site
# - {%- if cookiecutter.frontend_style == SPA %}
django_site_host: "{{ cookiecutter.spa_django_host_prefix | as_hostname }}.todo.example.com"
node_site_host: "todo.example.com"
# - {%- else %}
django_site_host: "todo.example.com"
# - {%- endif %}

# Sentry config
django_sentry_environment: "todo"
django_sentry_dsn: ""  # TODO: Set to correct value or remove the TODO
# - {%- if cookiecutter.frontend_style == SPA %}
razzle_sentry_environment: "todo"
razzle_sentry_dsn: ""  # TODO: Set to correct value or remove the TODO
# - {%- endif %}

# Django health-check access token
django_health_check_access_token: "TODO"

# - {% if cookiecutter.django_media_engine == GCS %}
django_gs_bucket_name: "TODO-ENV"
django_gs_project_id: "TODO-ENV"
# - {%- endif %}{% if cookiecutter.django_media_engine == S3 %}
# S3 bucket name to use
django_aws_storage_bucket_name: "TODO-ENV"
# - {%- endif %}

# Which compose file to use in the server
compose_file: "docker-compose.production.yml"

# What git branch to deploy to the server
#  For temporary deployments see `Deploying a different version` section in the README in ansible directory.
deployment_version: "master"

# Reminder email for letsencrypt certificates
letsencrypt_reminder_email: "todo@example.com"

# Allow/Block indexing via `X-Robots-Tag` header
#
# Set to true in test servers
disable_indexing: true
