- name: "Figure out the remote media directory"
  shell: "docker-compose -f {{ "{{ compose_file }}" }} config | yq -r '.services.django.volumes[]' | grep '/files/media' | cut -d: -f1"
  args:
    chdir: "{{ "{{ code_dir | mandatory }}" }}"
  register: "remote_media_directory"
  delegate_to: "{{ "{{ source_host | mandatory }}" }}"

- name: "Download media files from source host"
  shell: >
    rsync --delay-updates -F --compress --archive {{ "{{ source_host | mandatory }}" }}:{{ "{{ remote_media_directory.stdout | mandatory }}" }}/ {{ "{{ local_media_path }}" }}
  delegate_to: localhost
  vars:
    ansible_become: no
