
- name: "Run manage.py {{ "{{ command_params | mandatory }}" }}"
  command: >-
            docker-compose
# - {% if cookiecutter.build_in_ci == NO %}
            -f {{ "{{ compose_file "}} }}
# - {% endif %}
            run --rm
            --entrypoint 'bash -c "python manage.py {{ "{{ command_params | mandatory }}" }}"'
            django
  args:
      chdir: "{{ "{{ code_dir }}" }}"
  register: result


- debug:
      var: result
