- name: "Run preparation script"
  shell: "poetry run sh mirror-prepare.sh"
  delegate_to: localhost
  vars:
    ansible_become: no


- name: "Mirror the media files"
  import_tasks: mirror_media.yml
  tags:
    - media
    - files


- name: "Mirror the DB"
  import_tasks: mirror_db.yml
  tags:
    - db
    - database
