{%- raw -%}
- name: "Figure out the remote media directory"
  shell: "docker-compose -f {{ compose_file }} config | yq -r '.services.django.volumes[]' | grep '/files/media' | cut -d: -f1"
  args:
    chdir: "{{ code_dir }}"
  register: "remote_media_directory"


- name: "Download media files"
  synchronize:
    src: "{{ remote_media_directory.stdout }}/"
    dest: "{{ local_media_path }}"
    mode: pull
    set_remote_user: no
    recursive: yes
  delegate_to: localhost
  vars:
    ansible_become: no
{%- endraw %}
