{%- raw -%}
# Note: `aws-cli` must be installed locally to make this role work. E.g. `sudo pip install awscli`.

- name: "Use aws s3 command to download media files"
  delegate_to: localhost
  delegate_facts: true
  vars:
    ansible_become: no
  command: "aws s3 cp s3://{{ settings.AWS_STORAGE_BUCKET_NAME }}/media {{ local_media_path }} --recursive"
  environment:
    AWS_ACCESS_KEY_ID: "{{ settings.AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ settings.AWS_SECRET_ACCESS_KEY }}"
{%- endraw %}
