pipeline:
  build:
  # TODO: make sure this is the right base image. Default is your selected Python version plus Node 6.x, which might or
  #  might not exist depending on the selected Python version
    image: thorgate/python{{cookiecutter.python_version}}-node6
    commands:
      # Uses /wheelhouse (configured in the thorgate python images)
      - pip wheel -r requirements/local.txt -r requirements/production.txt

      # Create virtualenv and install dependencies from wheels
      - make venv
      - . ./venv/bin/activate
      - pip install --use-wheel --no-index -r requirements/local.txt -r requirements/production.txt

      # Install node packages
      - cd {{ cookiecutter.repo_name }}
      - npm install --silent --python=python2.7

      # Run tests
      - EDIT_SETTINGS=no make settings
      - make test
      - make quality

  # http://plugins.drone.io/drone-plugins/drone-slack/
  # slack:
  #   image: plugins/slack
  #   webhook: https://hooks.slack.com/services/TODO
  #   channel: {{ cookiecutter.repo_name }}
  #   username: drone
  #   when:
  #     branch: master
  #   template: |{% raw %}
  #     {{ uppercase build.status }} for {{ repo.name }} build #{{ build.number }}
  #     Commit {{ truncate build.commit 8 }} by {{ build.author }}; took {{ since job.started }}{% endraw %}
